CREATE TABLE notes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    text       CLOB,
    tag        varchar(255) NOT NULL,
    created_at TIMESTAMP
);